version: '3.9'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 3030
    volumes:
      - data:/var/lib/mysql

  bedrock:
    build:
      context: .
      dockerfile: ./build/bedrock.dockerfile
    container_name: bedrock-${id4884}-1334247545$2
    restart: always
    depends_on:
      - mariadb
    ports:
      - '9857:80'
    environment:
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_HOST: mariadb
      WP_ENV: '${WP_ENV}'
      WP_HOME: '${WP_HOME}'
      WP_SITEURL: '${WP_SITEURL}'
    volumes:
      - bedrock_uploads:/var/www/html/web/app/uploads

volumes:
  mariadb_data:
  bedrock_uploads:
