version: '3.9'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wpuser
      MARIADB_PASSWORD: wppassword
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "wpuser", "-pwppassword"]
      interval: 5s
      timeout: 5s
      retries: 5

  bedrock:
    build:
      context: .
      dockerfile: ./build/bedrock.dockerfile
    container_name: bedrock-container
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - '9857:80'
    environment:
      DB_NAME: wordpress
      DB_USER: wpuser
      DB_PASSWORD: wppassword
      DB_HOST: mariadb
      WP_ENV: development
      WP_HOME: http://localhost:9857
      WP_SITEURL: http://localhost:9857/wp
    volumes:
      - bedrock_uploads:/var/www/html/web/app/uploads

volumes:
  data:
  bedrock_uploads:
