version: '3.9'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "6854:3306"
    volumes:
      - data:/var/lib/mysql

  bedrock:
    build:
      context: .
      dockerfile: ./build/bedrock.dockerfile
    container_name: bedrock-container
    restart: always
    depends_on:
      - mariadb
    ports:
      - '9857:80'
    environment:
      DB_NAME: ${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      DB_HOST: mariadb
      WP_ENV: ${WP_ENV}
      WP_HOME: ${WP_HOME}
      WP_SITEURL: ${WP_SITEURL}
    volumes:
      - bedrock_uploads:/var/www/html/web/app/uploads

volumes:
  data:
  bedrock_uploads:
